server.port=8082
spring.application.name=ledger-service

spring.datasource.url=jdbc:postgresql://postgres:5432/omnistay_db
spring.datasource.username=postgres
spring.datasource.password=postgres_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/omnistay-realm
